# Generated by Django 4.0.3 on 2022-10-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(max_length=30)),
                ('style_name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('picture_url', models.URLField(null=True)),
                ('wardrobe_location', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
